Fix/config
axZerk/gulp-starter-kit pull request #10
Opened 2019-06-30 21:00 UTC by vbguard

Added default task - run in terminal command => ```gulp``` 
And deploy task by gh-pages - run command => ``` gulp deploy```

2019-06-30 23:43 UTC, luxplanjay requested changes

2019-06-30 23:43 UTC, luxplanjay commented on package.json
> +    "deploy": "gulp build && gulp deploy"
Надо использовать pre-хуки вместо `"deploy": "gulp build && gulp deploy"` 

`"predeploy": "gulp build"`
`"deploy": "gulp deploy"`

2019-06-30 23:43 UTC, luxplanjay commented on gulpfile.js
> +exports.default = start;
Так делать ненадо, gulp имя пакета и запуск без имени таска это пережиток прошлого. Представь npm вместо npm start. У взрослых людей все равно стоят алиасы.

2019-06-30 23:43 UTC, luxplanjay commented on gulpfile.js
> +  ghPages.publish(path.join(process.cwd(), './build'), cb);
1. В куда его будет деплоить?
2. resolve, __dirname и 'build'

2019-07-01 07:55 UTC, vbguard commented on gulpfile.js
> +  ghPages.publish(path.join(process.cwd(), './build'), cb);
1. У дефолтну гілку gh-pages, добавив опції, щоб була можливість поміняти на іншу гілку

2019-07-01 07:58 UTC, vbguard commented on gulpfile.js
> +  ghPages.publish(path.join(process.cwd(), './build'), cb);
2. Пофіксив на абсолютний шлях дерикторії

2019-07-01 07:58 UTC, vbguard commented on gulpfile.js
> +exports.default = start;
Видалив дефолтний експорт

2019-07-10 16:02 UTC, merged